use_frameworks!

platform :ios, '9.0'
inhibit_all_warnings!

target 'HKChineseWords_Example' do
  pod 'HKChineseWords', :path => '../'

  target 'HKChineseWords_Tests' do
    inherit! :search_paths

    
  end
end
