language: objective-c
osx_image: xcode8.2
podfile: Example/Podfile
xcode_sdk: iphonesimulator10.2
script:
- xcodebuild -workspace Example/HKChineseWords.xcworkspace -scheme "HKChineseWords_Example" -destination "platform=iOS Simulator,name=iPhone 7"

