language: objective-c
osx_image: xcode8.2
podfile: Example/Podfile
script:
- xcodebuild -workspace Example/HKChineseWords.xcworkspace -scheme "HKChineseWords_Example" -destination "platform=iOS Simulator,id=8188B40E-F57F-4519-AC47-E43D884B9016,OS=10.2,name=iPhone 7"
