language: objective-c
osx_image: xcode8.2
podfile: Example/Podfile
script:
- xcodebuild -workspace Example/HKChineseWords.xcworkspace -scheme "HKChineseWords_Example" -destination "platform=iOS Simulator,OS=10.2,name=iPhone 7"
